# Generated by Django 4.0.3 on 2022-03-03 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotations',
            old_name='annotations',
            new_name='annotation',
        ),
    ]
