# Generated by Django 4.0.3 on 2022-03-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_rename_annotations_annotations_annotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotations',
            name='selected_text',
            field=models.CharField(default='DEFAULT', max_length=64),
        ),
        migrations.AlterField(
            model_name='annotations',
            name='annotation',
            field=models.CharField(default='DEFAULT', max_length=64),
        ),
    ]
